#!/usr/bin/env bash
set -eu -o pipefail

: <<DESC
Ensure that all submodule references have already been pushed to the remote origin.
DESC


while read _ path _; do
    commit=$(git ls-tree HEAD $path | awk '{print $3;}')
    pushd $path >/dev/null
    if [[ -z $(git branch -r --contains $commit 2>/dev/null) ]]; then
        printf "\e[1;33m%s\e[1;31m submodule has not been pushed to remote\e[0m\n" "$path" >&2
        git log -n1 --oneline HEAD >&2
        exit 1
    fi
    popd >/dev/null
done < <(git submodule)
