#!/usr/bin/env bash
set -eu -o pipefail

: <<DESC
Ensure your branch names contain a Jira issue id
DESC

: <<'HELP'
Mark branches as protected by adding them to a .protected file in the top-level
repository directory. By default, only master is protected. Works best if run
after pre-commit-jira-protect-branch.

If running this as a standalone script, say through `git hooks run pre-commit-jira-branch-name`,
one may provide any non-empty command-line parameter to force the branch creation flow (it will be
otherwise ignored).
HELP

# Get our useful functions
# shellcheck source=included/lib/jira.sh
. "$(dirname "${BASH_SOURCE[@]}")/../../lib/jira.sh" "$(dirname "${BASH_SOURCE[@]}")/../../lib"

branch=$(git symbolic-ref --short HEAD)
if (( $# )); then
    move_to_branch "$(jira_ensure_conforming_branch_name "$(jira_get_new_branch_name)")"
else
    if ! commit_in_progress; then
        printf "${c_action}%s${c_reset}\\n" "Not a new commit, nothing to be done"
        exit 0
    fi

    if ! is_protected_branch "$branch"; then
        move_to_branch "$(jira_ensure_conforming_branch_name "$branch")"
    fi
fi
